### ISSUE TITLE
xteve can´t create folder

### ISSUE THREAD

**Issue by loolery** [bl0m1/xtevedocker#12]
Every try to start the container ends with this:

`2020/01/23 15:55:00 [xTeVe] [ERROR] mkdir /home/xteve/.xteve/backup/: permission denied (Folder could not be created.) - EC: 1070

,2020/01/23 15:55:00 [xTeVe] [ERROR] mkdir /home/xteve/.xteve/backup/: permission denied () - EC: 0
`
??

**Comment by papapep514** [comment]
I second that.

**Comment by Fotzenfickerfuenftausend** [comment]
Unfortunately, I do face the same problem. Did you manage to fix it, @loolery @papapep514?

**Comment by papapep514** [comment]
Gave up, installed the windows version. That one works :)

**Comment by Fotzenfickerfuenftausend** [comment]
Thank you! Did so as well, now it works just fine.

**Comment by LostOnTheLine** [comment]
This problem still is a problem, them using a different version doesn't solve the problem, it just means they gave up
