### ISSUE TITLE
Cannot change timezone

### ISSUE THREAD

**Issue by gatalon** [bl0m1/xtevedocker#14]
I cannot change timezone, cannot switch to root use su and install package use apk. can you help?

**Comment by bl0m1** [comment]
You are correct currently there is no option available. I'll have a look if this can be managed by an env variable 🙂

**Comment by solipsist01** [comment]
just add tzdata

apk add tzdata

https://www.grainger.xyz/timezone-in-docker-alpine-not-using-environment-variable-tz/

**Comment by bl0m1** [comment]
timezone can now be set if you are using the latest release (released a few minutes ago)
Shutout to https://github.com/abuhamsa for providing a PR!
