### ISSUE TITLE
Change default port possible?

### ISSUE THREAD

**Issue by CelticWebSolutions** [bl0m1/xtevedocker#17]
Firstly, thanks for taking the time to setup this image for us.

I see that for some reason the execution common in this image sets the port, which means that changing it in the settings.json has no effect, is there a reason why you launch with a port override number too?  I know I can just set the port forward in the docker image but then Xteve gives urls with the wrong port.

Is there an environment variable that allows changing the port?  Or perhaps a way to change the execution command so that it doesn't override the port in settings?

I look forward to your response.

**Comment by bl0m1** [comment]
You can change the port using a custom cmd.
Default is "-port=34400" however you can change this to whatever port you want :)
