### ISSUE TITLE
Plex - XTeve - IPTV

### ISSUE THREAD

**Issue by williamcaput** [bl0m1/xtevedocker#21]
Having issues getting Plex - XTeve - IPTV working reliably. 

Provided XTeve the M3U file under 'Playlist'. Provided the EPG under 'XMLTV'.
Mapped 47 channels that I wanted under 'Mapping'.

Provide Plex my M3U from Xteve (192.168.x.x:34000/m3u/xteve.m3u)
Provide Plex the EPG from Xteve (192.168.x.x:34000/xmltv/xteve.xml)

A few channels will show up, but never consistently. Channels aren't named, just 1004, 1005, etc. Unknown airing on most of them.  Often I get: Playback Error
Could not tune channel. Please check your tuner or antenna.

Returning to Plex - Live TV and DVR it shows:  Device not found. Ensure your device is powered on and connected to your network.

Often lots of buffering too.

Works fine with my phone and Web Video Caster.

Any help is appreciated.

**Comment by bl0m1** [comment]
Closing this issue since it is a few years old. In case you would still experience issues with the latest version I would suggest you checking with the xteve team over at their gitrepo: https://github.com/xteve-project/xTeVe
