### ISSUE TITLE
Starting Problem

### ISSUE THREAD

**Issue by Rapptor33** [bl0m1/xtevedocker#23]
Hello,

I am running Docker on a Synology NAS.
I stopped the container inside Docker, now when I want to restart it it apears an error.

`standard_init_linux.go:230: exec user process caused: exec format error`

Version:
`2021/06/09 09:35:27 [xTeVe] Version:               2.1.2 Build: 0121`

Regards

**Comment by pennyandsean** [comment]
I get this too.  Sorry, not a very useful comment I know.  Except, you're not the only one.
