### ISSUE TITLE
How to connect to the web ui?

### ISSUE THREAD

**Issue by oatmealm** [bl0m1/xtevedocker#24]
When I run the container using an internal docker ip I can't reach it from another computer on the network, can I? When I ran in host mode port 1900 is already taken by Jellyfin.

**Comment by bl0m1** [comment]
> When I run the container using an internal docker ip I can't reach it from another computer on the network, can I? When I ran in host mode port 1900 is already taken by Jellyfin.

Hello, by default port 34400 is used. If you cannot connect on this port could you share the docker command used to start the container?

**Comment by oatmealm** [comment]
Thank you. Misunderstanding on my part. I've got it now running as expected!
