### ISSUE TITLE
Invalid M3U

### ISSUE THREAD

**Issue by sankosme** [bl0m1/xtevedocker#25]
Hi, try to load a m3u file from my webif (dreambox dm800), any help for this problem?
![image](https://user-images.githubusercontent.com/48553106/153863239-e5d60336-ca98-45c8-b6d2-7530648ff883.png)
Sample m3u:
`#EXTM3U 
#EXTVLCOPT--http-reconnect=true
#EXTINF:-1,LA 1 HD
http://192.168.2.252:80/1:0:19:7863:41A:1:C00000:0:0:0:
#EXTINF:-1,LA 2
http://192.168.2.252:80/1:0:1:7474:3F0:1:C00000:0:0:0:
#EXTINF:-1,TVGA HD EUROPA
http://192.168.2.252:80/1:0:1:18F1:3F4:1:C00000:0:0:0:
#EXTINF:-1,ANTENA 3 HD
http://192.168.2.252:80/1:0:19:7534:426:1:C00000:0:0:0:`

**Comment by bl0m1** [comment]
Hello, I have created an updated container that is now published on dockerhub.
Could you test the latest one?

If that doesn't work I would suggest checking with the xteve team over at their repo: https://github.com/xteve-project/xTeVe

Hope you are solving your problem :)
