### ISSUE TITLE
Can't get in Plex the XML created

### ISSUE THREAD

**Issue by sampleslaya** [bl0m1/xtevedocker#3]
Hello.

I've mapped all my channels to my EPG XML.

But in Plex i must insert the local path to the new generated XEPG URL (that is stored in /root/xteve/data/xteve.xml) but this location is unreachable.

How can i provide the local path to th XEPG URL?

Thanks.

**Comment by plozachm** [comment]
I think you can just provide the url:
![image](https://user-images.githubusercontent.com/16304323/62003139-9216b480-b112-11e9-9d8b-314cea732aa1.png)
