### ISSUE TITLE
Does it make sense to have this container running though a VPN??

### ISSUE THREAD

**Issue by Shifter2600** [bl0m1/xtevedocker#7]
Does it make sense to have this container running though a VPN?? I have seen other container have built in variables for PIA VPN or OpenVPN. I was just wondering since the M3U and XMLTV communication is all http it probably would be best to have the VPN..

**Comment by bl0m1** [comment]
If you would like to send the traffic over VPN it would make more sene to handle this in your firewall.

I assume you only connect to this service locally or would it also be of interest exposing this service thru the VPN? there is some providers that allows port-forward.

I will let this issue stay open to check if there is more interest in this feature.

**Comment by derekslenk** [comment]
I run an openvpn client docker image and have that as my network service with a shared port...and connect to the VPN that way. It works and you can connect a bunch of docker containers, but it is not straightforward
