### ISSUE TITLE
Do you intend to add support for the ffmpeg & Vlc features

### ISSUE THREAD

**Issue by smurfster** [bl0m1/xtevedocker#8]
Hi,

I've seen that xteve supports different types of buffer now, are you going to support them?

regards

**Comment by bl0m1** [comment]
Hello!

Let me have a look at whats needed during this week and I'll revert back with more information regarding this :)

**Comment by xboxhacks** [comment]
i'm having issues with local streams. Seems only vlc and ffmpeg will work, any update on this enhancement?

**Comment by bl0m1** [comment]
A new version of this image is currently being built and will be available for download in a few minutes
