### ISSUE TITLE
Cannot Connect to Port

### ISSUE THREAD

**Issue by stevenjev** [bl0m1/xtevedocker#9]
When launching the container I am getting an error: 

"curl: (7) Failed to connect to localhost port 34400: Connection refused "

I've been able to access this container without issue before. I've launched the docker container as host and port mapped (following the instructions in the read me). 

I've restarted the computer. No other containers or processes are using port 34400. Running the container on Ubuntu 18.04.3 LTS and trying to access on other computers within the same home network.

Output log of the Xteve docker container shows that it is running, without errors, and appears that only the port connection for is failing.

**Comment by stevenjev** [comment]
I forked the project and removed lines 27 & 28:

`HEALTHCHECK --interval=30s --start-period=30s --retries=3 --timeout=10s \ `
  `CMD curl -f http://localhost:34400/ || exit 1`

The errors went away and the container started without issue.

**Comment by bl0m1** [comment]
I assume this is due to an old docker version.

The health-check was implemented in Docker 1.12

What version of docker are you running?

**Comment by stevenjev** [comment]
I started with a new VM and (subsequently the latest version of Docker) the issue went away. You must have been right about running an older docker version. Closing, thanks!
